moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - left_arm_controller
    - right_arm_controller
    - left_gripper_controller
    - right_gripper_controller

  left_arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - left_j1
      - left_j2
      - left_j3
      - left_j4
      - left_j5
      - left_j6

  right_arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - right_j1
      - right_j2
      - right_j3
      - right_j4
      - right_j5
      - right_j6

  left_gripper_controller:
    type: GripperCommand
    action_ns: gripper_action
    default: true
    joints:
      - left_left_finger_joint

  right_gripper_controller:
    type: GripperCommand
    action_ns: gripper_action
    default: true
    joints:
      - right_left_finger_joint
